/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/api-client.ts
var import_obsidian = require("obsidian");
var ApiError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
    this.name = "ApiError";
  }
};
function describeApiError(error) {
  if (error instanceof ApiError) {
    if (error.status === 401)
      return "\u8BA4\u8BC1\u5931\u8D25\uFF08401\uFF09\uFF1A\u8BF7\u68C0\u67E5 Obsidian \u8BBE\u7F6E\u4E2D\u7684 Webhook Secret\u3002";
    if (error.status === 404)
      return "\u63A5\u53E3\u4E0D\u5B58\u5728\uFF08404\uFF09\uFF1A\u8BF7\u68C0\u67E5\u540C\u6B65\u670D\u52A1\u5730\u5740\uFF0C\u6216\u786E\u8BA4\u670D\u52A1\u5668\u5DF2\u66F4\u65B0\u3002";
    if (error.status === 503)
      return `\u670D\u52A1\u4E0D\u53EF\u7528\uFF08503\uFF09\uFF1A${error.message}`;
    return `\u670D\u52A1\u5668\u8FD4\u56DE ${error.status}\uFF1A${error.message}`;
  }
  const message = error instanceof Error ? error.message : String(error);
  if (/network|fetch|connect|socket|dns|timeout|certificate/i.test(message)) {
    return `\u65E0\u6CD5\u8FDE\u63A5\u670D\u52A1\u5668\uFF1A${message}`;
  }
  return message || "\u672A\u77E5\u9519\u8BEF";
}
function apiBase(endpoint) {
  const raw = endpoint.trim();
  try {
    const url = new URL(raw);
    if (url.pathname.endsWith("/api/sync"))
      url.pathname = "/api/v1";
    else if (!url.pathname.includes("/api/v1"))
      url.pathname = "/api/v1";
    url.pathname = url.pathname.replace(/\/+$/, "");
    return url.toString().replace(/\/$/, "");
  } catch (e) {
    return raw.replace(/\/api\/sync\/?$/, "/api/v1").replace(/\/$/, "");
  }
}
var ApiClient = class {
  constructor(settings) {
    this.base = apiBase(settings.syncEndpoint);
    this.secret = settings.webhookSecret;
  }
  async request(path, method = "GET", body) {
    var _a;
    let response;
    try {
      response = await (0, import_obsidian.requestUrl)({
        url: `${this.base}${path}`,
        method,
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.secret}`
        },
        body: body === void 0 ? void 0 : JSON.stringify(body),
        throw: false
      });
    } catch (error) {
      throw new Error(`\u8BF7\u6C42 ${this.base}${path} \u5931\u8D25\uFF1A${error instanceof Error ? error.message : String(error)}`);
    }
    if (response.status < 200 || response.status >= 300) {
      let message = response.text || `HTTP ${response.status}`;
      try {
        message = (_a = JSON.parse(response.text).message) != null ? _a : message;
      } catch (e) {
      }
      throw new ApiError(response.status, message);
    }
    return response.json;
  }
  createJob(localManifest) {
    return this.request("/jobs", "POST", { clientId: "obsidian", localManifest });
  }
  getJob(id) {
    return this.request(`/jobs/${id}`);
  }
  updateArticle(jobId, article) {
    return this.request(`/jobs/${jobId}/articles/${article.id}`, "PUT", {
      revision: article.revision,
      metadata: article.metadata,
      content: article.content,
      status: article.status
    });
  }
  getTaxonomy() {
    return this.request("/taxonomy");
  }
  getTaxonomyUsage() {
    return this.request("/taxonomy/usage");
  }
  saveTaxonomy(value) {
    return this.request("/taxonomy", "PUT", value);
  }
  testConnection() {
    return this.getTaxonomy();
  }
  publish(jobId, articles) {
    return this.request(`/jobs/${jobId}/publish`, "POST", {
      articles: articles.map((article) => ({ id: article.id, revision: article.revision, hash: article.currentHash })),
      includeTaxonomy: true
    });
  }
};

// src/article-manager-view.ts
var import_obsidian3 = require("obsidian");

// src/local-ai.ts
var import_obsidian2 = require("obsidian");
function text(value) {
  return typeof value === "string" ? value.trim() : "";
}
function extractJSONObject(value) {
  let cleaned = value.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start >= 0 && end >= start)
    cleaned = cleaned.slice(start, end + 1);
  try {
    return JSON.parse(cleaned);
  } catch (error) {
    throw new Error(`AI \u8FD4\u56DE\u5185\u5BB9\u4E0D\u662F\u5408\u6CD5 JSON\uFF1A${error instanceof Error ? error.message : String(error)}`);
  }
}
function normalizeSuggestion(raw, taxonomy, maxProposedTags) {
  const categoryMap = new Map(taxonomy.categories.filter((item) => item.enabled).map((item) => [item.name.toLowerCase(), item.name]));
  const tagMap = /* @__PURE__ */ new Map();
  for (const tag of taxonomy.tags.filter((item) => item.enabled && item.aiSelectable)) {
    tagMap.set(tag.name.toLowerCase(), tag.name);
    for (const alias of tag.aliases)
      tagMap.set(alias.trim().toLowerCase(), tag.name);
  }
  let category = text(raw.category);
  let proposedCategory = null;
  const canonicalCategory = categoryMap.get(category.toLowerCase());
  if (canonicalCategory)
    category = canonicalCategory;
  else if (category) {
    proposedCategory = { name: category, reason: "AI \u8FD4\u56DE\u4E86\u5206\u7C7B\u5E93\u5916\u7684\u5206\u7C7B" };
    category = "";
  }
  if (raw.proposedCategory) {
    const name = text(raw.proposedCategory.name);
    const existing = categoryMap.get(name.toLowerCase());
    if (!category && existing)
      category = existing;
    else if (name && !existing)
      proposedCategory = { name, reason: text(raw.proposedCategory.reason) || "\u73B0\u6709\u5206\u7C7B\u4E0D\u9002\u5408\u8FD9\u7BC7\u6587\u7AE0" };
  }
  const selectedTags = [];
  const proposedTags = [];
  const selectedSeen = /* @__PURE__ */ new Set();
  const proposedSeen = /* @__PURE__ */ new Set();
  if (Array.isArray(raw.selectedTags)) {
    for (const item of raw.selectedTags) {
      const name = text(item);
      const canonical = tagMap.get(name.toLowerCase());
      if (canonical && !selectedSeen.has(canonical)) {
        selectedTags.push(canonical);
        selectedSeen.add(canonical);
      } else if (name && !canonical && !proposedSeen.has(name.toLowerCase())) {
        proposedTags.push({ name, reason: "AI \u8FD4\u56DE\u4E86\u6807\u7B7E\u5E93\u5916\u7684\u6807\u7B7E" });
        proposedSeen.add(name.toLowerCase());
      }
    }
  }
  if (Array.isArray(raw.proposedTags)) {
    for (const item of raw.proposedTags) {
      if (!item || typeof item !== "object")
        continue;
      const candidate = item;
      const name = text(candidate.name);
      const canonical = tagMap.get(name.toLowerCase());
      if (canonical && !selectedSeen.has(canonical)) {
        selectedTags.push(canonical);
        selectedSeen.add(canonical);
      } else if (name && !canonical && !proposedSeen.has(name.toLowerCase())) {
        proposedTags.push({ name, reason: text(candidate.reason) || "\u73B0\u6709\u6807\u7B7E\u65E0\u6CD5\u51C6\u786E\u8868\u8FBE\u6587\u7AE0\u4E3B\u9898" });
        proposedSeen.add(name.toLowerCase());
      }
    }
  }
  return {
    description: text(raw.description),
    category,
    proposedCategory,
    selectedTags: selectedTags.slice(0, 6),
    proposedTags: proposedTags.slice(0, Math.max(0, Math.min(10, maxProposedTags)))
  };
}
async function analyzeArticleLocally(settings, taxonomy, article) {
  var _a, _b, _c, _d, _e, _f;
  const baseUrl = settings.aiBaseUrl.trim().replace(/\/+$/, "");
  if (!baseUrl)
    throw new Error("\u8BF7\u5148\u914D\u7F6E AI API \u5730\u5740\u3002");
  if (!settings.aiApiKey.trim())
    throw new Error("\u8BF7\u5148\u914D\u7F6E AI API Key\u3002");
  if (!settings.aiModel.trim())
    throw new Error("\u8BF7\u5148\u914D\u7F6E AI \u6A21\u578B\u3002");
  const endpoint = /\/chat\/completions$/i.test(baseUrl) ? baseUrl : `${baseUrl}/chat/completions`;
  const categories = taxonomy.categories.filter((item) => item.enabled).map((item) => `- ${item.name}\uFF1A${item.description || "\u65E0\u8BF4\u660E"}`).join("\n") || "\uFF08\u65E0\uFF09";
  const tags = taxonomy.tags.filter((item) => item.enabled && item.aiSelectable).map((item) => `- ${item.name}\uFF1A${item.description || "\u65E0\u8BF4\u660E"}`).join("\n") || "\uFF08\u65E0\uFF09";
  const prompt = `${settings.aiMetadataPrompt}

${settings.aiTagRules}

\u8BF7\u53EA\u8FD4\u56DE\u4E00\u4E2A JSON \u5BF9\u8C61\uFF0C\u4E0D\u8981\u8FD4\u56DE Markdown\u3002\u683C\u5F0F\uFF1A
{"description":"\u6458\u8981","category":"\u53EA\u80FD\u662F\u5DF2\u6709\u5206\u7C7B\u6216\u7A7A\u5B57\u7B26\u4E32","proposedCategory":{"name":"\u65B0\u5206\u7C7B","reason":"\u7406\u7531"},"selectedTags":["\u53EA\u80FD\u662F\u5DF2\u6709\u6807\u7B7E"],"proposedTags":[{"name":"\u65B0\u6807\u7B7E","reason":"\u7406\u7531"}]}

\u89C4\u5219\uFF1A
1. category \u53EA\u80FD\u4ECE\u5DF2\u6709\u5206\u7C7B\u9009\u62E9\uFF1B\u6CA1\u6709\u5408\u9002\u5206\u7C7B\u65F6\u7559\u7A7A\uFF0C\u5E76\u586B\u5199 proposedCategory\uFF0C\u5426\u5219 proposedCategory \u4E3A null\u3002
2. selectedTags \u53EA\u80FD\u4ECE\u5DF2\u6709\u6807\u7B7E\u9009\u62E9\uFF1B\u65B0\u6807\u7B7E\u53EA\u80FD\u653E\u5165 proposedTags\u3002
3. proposedTags \u6700\u591A ${settings.aiMaxProposedTags} \u4E2A\u3002

\u5DF2\u6709\u5206\u7C7B\uFF1A
${categories}

\u5DF2\u6709\u6807\u7B7E\uFF1A
${tags}

\u6587\u4EF6\u540D\uFF1A${article.filename}
\u5F53\u524D\u6807\u9898\uFF1A${article.metadata.title || "\u65E0"}
\u6B63\u6587\uFF1A
${article.content.slice(0, 12e3)}`;
  let response;
  try {
    response = await (0, import_obsidian2.requestUrl)({
      url: endpoint,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${settings.aiApiKey.trim()}` },
      body: JSON.stringify({
        model: settings.aiModel.trim(),
        messages: [
          { role: "system", content: settings.aiSystemPrompt },
          { role: "user", content: prompt }
        ],
        max_tokens: 2048
      }),
      throw: false
    });
  } catch (error) {
    throw new Error(`\u65E0\u6CD5\u8FDE\u63A5 AI \u670D\u52A1\uFF1A${error instanceof Error ? error.message : String(error)}`);
  }
  if (response.status < 200 || response.status >= 300) {
    let message = response.text || `HTTP ${response.status}`;
    try {
      const data2 = JSON.parse(response.text);
      message = (_c = (_b = (_a = data2.error) == null ? void 0 : _a.message) != null ? _b : data2.message) != null ? _c : message;
    } catch (e) {
    }
    throw new Error(`AI \u670D\u52A1\u8FD4\u56DE ${response.status}\uFF1A${message}`);
  }
  const data = response.json;
  const content = (_f = (_e = (_d = data.choices) == null ? void 0 : _d[0]) == null ? void 0 : _e.message) == null ? void 0 : _f.content;
  if (typeof content !== "string" || !content.trim())
    throw new Error("AI \u6CA1\u6709\u8FD4\u56DE\u53EF\u7528\u5185\u5BB9\u3002");
  return normalizeSuggestion(extractJSONObject(content), taxonomy, settings.aiMaxProposedTags);
}

// src/article-manager-view.ts
var ARTICLE_MANAGER_VIEW = "flash-thought-article-manager";
async function sha256(value) {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest)).map((item) => item.toString(16).padStart(2, "0")).join("");
}
var ArticleManagerView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.job = null;
    this.taxonomy = null;
    this.taxonomyState = "loading";
    this.taxonomyError = "";
    this.taxonomyUsage = {};
    this.categoryUsage = {};
    this.taxonomyUsageLoaded = false;
    this.taxonomyTab = "tags";
    this.tagSearch = "";
    this.tagFilter = "all";
    this.activeArticleId = "";
    this.selected = /* @__PURE__ */ new Set();
    this.dirtyArticles = /* @__PURE__ */ new Set();
    this.showTaxonomy = false;
    this.pollTimer = null;
    this.aiRunning = false;
    this.aiProgress = "";
    this.plugin = plugin;
  }
  getViewType() {
    return ARTICLE_MANAGER_VIEW;
  }
  getDisplayText() {
    return "\u4E00\u4E2A\u95EA\u5FF5 \xB7 \u5185\u5BB9\u7BA1\u7406";
  }
  getIcon() {
    return "layout-dashboard";
  }
  async onOpen() {
    this.contentEl.addClass("vermilion-manager");
    this.render();
    await Promise.all([
      this.loadTaxonomy(),
      (async () => {
        var _a, _b, _c;
        if (!this.plugin.settings.activeJobId)
          return;
        try {
          this.job = await this.plugin.api.getJob(this.plugin.settings.activeJobId);
          this.applyCachedSuggestions();
          this.activeArticleId = (_c = (_b = (_a = this.job.articles) == null ? void 0 : _a[0]) == null ? void 0 : _b.id) != null ? _c : "";
        } catch (error) {
          new import_obsidian3.Notice(`\u52A0\u8F7D\u6587\u7AE0\u4EFB\u52A1\u5931\u8D25\uFF1A${describeApiError(error)}`);
        }
      })()
    ]);
    this.render();
    this.schedulePoll();
  }
  async loadTaxonomy(showNotice = false) {
    var _a, _b;
    this.taxonomyState = "loading";
    this.taxonomyError = "";
    this.render();
    try {
      this.taxonomy = await this.plugin.api.getTaxonomy();
      this.taxonomyState = "loaded";
      try {
        const usage = await this.plugin.api.getTaxonomyUsage();
        this.taxonomyUsage = (_a = usage.tags) != null ? _a : {};
        this.categoryUsage = (_b = usage.categories) != null ? _b : {};
        this.taxonomyUsageLoaded = true;
      } catch (error) {
        this.taxonomyUsage = {};
        this.taxonomyUsageLoaded = false;
        if (!(error instanceof ApiError && error.status === 404))
          console.warn("Failed to load taxonomy usage", error);
      }
      if (showNotice)
        new import_obsidian3.Notice(`\u6807\u7B7E\u5E93\u52A0\u8F7D\u6210\u529F\uFF1A${this.taxonomy.tags.length} \u4E2A\u6807\u7B7E\u3002`);
    } catch (error) {
      this.taxonomy = null;
      this.taxonomyState = "error";
      this.taxonomyError = describeApiError(error);
      if (showNotice)
        new import_obsidian3.Notice(`\u6807\u7B7E\u5E93\u52A0\u8F7D\u5931\u8D25\uFF1A${this.taxonomyError}`);
    } finally {
      this.render();
    }
  }
  async onClose() {
    if (this.pollTimer !== null)
      window.clearTimeout(this.pollTimer);
  }
  async prepareSync() {
    try {
      const manifest = await this.collectLocalManifest();
      this.job = await this.plugin.api.createJob(manifest);
      this.plugin.settings.activeJobId = this.job.id;
      await this.plugin.saveSettings();
      this.activeArticleId = "";
      this.selected.clear();
      this.dirtyArticles.clear();
      this.plugin.settings.aiSuggestionJobId = this.job.id;
      this.plugin.settings.aiSuggestions = {};
      await this.plugin.saveSettings();
      this.showTaxonomy = false;
      this.render();
      this.schedulePoll(true);
      new import_obsidian3.Notice("\u5904\u7406\u4EFB\u52A1\u5DF2\u521B\u5EFA\uFF0C\u4E0D\u4F1A\u81EA\u52A8\u53D1\u5E03\u3002");
    } catch (error) {
      new import_obsidian3.Notice(`\u521B\u5EFA\u4EFB\u52A1\u5931\u8D25\uFF1A${error.message}`);
    }
  }
  async refreshJob() {
    var _a, _b, _c;
    if (!this.plugin.settings.activeJobId)
      return;
    if (this.dirtyArticles.size > 0) {
      new import_obsidian3.Notice("\u5B58\u5728\u672A\u4FDD\u5B58\u7684\u6587\u7AE0\uFF0C\u5DF2\u8DF3\u8FC7\u5237\u65B0\u3002");
      return;
    }
    try {
      this.job = await this.plugin.api.getJob(this.plugin.settings.activeJobId);
      this.applyCachedSuggestions();
      if (!this.activeArticleId)
        this.activeArticleId = (_c = (_b = (_a = this.job.articles) == null ? void 0 : _a[0]) == null ? void 0 : _b.id) != null ? _c : "";
      this.render();
    } catch (error) {
      new import_obsidian3.Notice(`\u5237\u65B0\u4EFB\u52A1\u5931\u8D25\uFF1A${error.message}`);
    }
  }
  schedulePoll(force = false) {
    if (this.pollTimer !== null)
      window.clearTimeout(this.pollTimer);
    const running = this.job && ["queued", "syncing", "analyzing", "publishing"].includes(this.job.status);
    if (!force && !running)
      return;
    this.pollTimer = window.setTimeout(async () => {
      await this.refreshJob();
      this.schedulePoll();
    }, 1500);
  }
  render() {
    var _a, _b, _c, _d;
    const root = this.contentEl;
    root.empty();
    const toolbar = root.createDiv({ cls: "vermilion-toolbar" });
    toolbar.createEl("button", { text: "\u83B7\u53D6\u5E76\u5904\u7406\u6587\u7AE0", cls: "mod-cta" }).onclick = () => void this.prepareSync();
    const refreshButton = toolbar.createEl("button", { text: "\u5237\u65B0\u72B6\u6001" });
    refreshButton.title = "\u4EC5\u91CD\u65B0\u8BFB\u53D6\u670D\u52A1\u5668\u4EFB\u52A1\u72B6\u6001\uFF0C\u4E0D\u4F1A\u8FD0\u884C AI \u5206\u6790";
    refreshButton.onclick = () => void this.refreshJob();
    const aiButton = toolbar.createEl("button", { text: this.aiRunning ? "AI \u5206\u6790\u4E2D\u2026" : "AI \u5206\u6790\u5F85\u5904\u7406" });
    aiButton.disabled = this.aiRunning || !((_b = (_a = this.job) == null ? void 0 : _a.articles) == null ? void 0 : _b.length);
    aiButton.onclick = () => void this.analyzePendingArticles();
    toolbar.createEl("button", { text: this.showTaxonomy ? "\u8FD4\u56DE\u6587\u7AE0" : "\u5206\u7C7B\u4E0E\u6807\u7B7E" }).onclick = () => {
      this.showTaxonomy = !this.showTaxonomy;
      this.render();
    };
    const publishButton = toolbar.createEl("button", { text: `\u53D1\u5E03\u6240\u9009 (${this.selected.size})`, cls: "mod-cta" });
    publishButton.disabled = this.selected.size === 0 || !this.job || this.job.status === "publishing";
    publishButton.onclick = () => void this.publishSelected();
    if (this.job) {
      const status = root.createDiv({ cls: "vermilion-job-status" });
      status.createSpan({ text: `${this.job.message} \xB7 ${this.job.progress}%` });
      const progress = status.createEl("progress");
      progress.max = 100;
      progress.value = this.job.progress;
      if (this.job.publishedSha)
        status.createEl("code", { text: this.job.publishedSha.slice(0, 12) });
    }
    if (this.aiProgress)
      root.createDiv({ cls: "vermilion-ai-progress", text: this.aiProgress });
    if (this.showTaxonomy) {
      this.renderTaxonomy(root);
      return;
    }
    if (!this.job) {
      root.createDiv({ cls: "vermilion-empty", text: "\u70B9\u51FB\u201C\u83B7\u53D6\u5E76\u5904\u7406\u6587\u7AE0\u201D\u521B\u5EFA\u4E00\u4E2A\u5F85\u5BA1\u6838\u4EFB\u52A1\u3002" });
      return;
    }
    if (!((_c = this.job.articles) == null ? void 0 : _c.length)) {
      root.createDiv({ cls: "vermilion-empty", text: this.job.status === "failed" ? this.job.message : "\u670D\u52A1\u5668\u6B63\u5728\u5904\u7406\u6587\u7AE0\u2026\u2026" });
      return;
    }
    const layout = root.createDiv({ cls: "vermilion-layout" });
    this.renderArticleList(layout.createDiv({ cls: "vermilion-list" }));
    const active = (_d = this.job.articles.find((article) => article.id === this.activeArticleId)) != null ? _d : this.job.articles[0];
    this.activeArticleId = active.id;
    this.renderEditor(layout.createDiv({ cls: "vermilion-editor" }), active);
    void this.renderPreview(layout.createDiv({ cls: "vermilion-preview" }), active);
  }
  renderArticleList(container) {
    var _a, _b;
    container.createEl("h3", { text: "\u6587\u7AE0" });
    for (const article of (_b = (_a = this.job) == null ? void 0 : _a.articles) != null ? _b : []) {
      const row = container.createDiv({ cls: `vermilion-list-item ${article.id === this.activeArticleId ? "is-active" : ""}` });
      const checkbox = row.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selected.has(article.id);
      checkbox.onchange = () => {
        if (checkbox.checked)
          this.selected.add(article.id);
        else
          this.selected.delete(article.id);
        this.render();
      };
      const text2 = row.createDiv({ cls: "vermilion-list-label" });
      text2.createDiv({ text: article.metadata.title || article.filename });
      text2.createEl("small", { text: article.status });
      text2.onclick = () => {
        this.activeArticleId = article.id;
        this.render();
      };
    }
  }
  labeledInput(container, label, value, onChange, multiline = false) {
    const field = container.createDiv({ cls: "vermilion-field" });
    field.createEl("label", { text: label });
    const input = multiline ? field.createEl("textarea") : field.createEl("input", { type: "text" });
    input.value = value;
    input.oninput = () => onChange(input.value);
    return input;
  }
  renderCategorySelect(container, article) {
    var _a, _b, _c;
    const field = container.createDiv({ cls: "vermilion-field" });
    field.createEl("label", { text: "\u5206\u7C7B" });
    const select = field.createEl("select");
    select.createEl("option", { text: "\u672A\u5206\u7C7B", value: "" });
    const enabled = (_b = (_a = this.taxonomy) == null ? void 0 : _a.categories.filter((category) => category.enabled)) != null ? _b : [];
    const current = (_c = article.metadata.category) != null ? _c : "";
    if (current && !enabled.some((category) => category.name === current)) {
      select.createEl("option", { text: `${current}\uFF08\u672A\u6279\u51C6\u6216\u5DF2\u505C\u7528\uFF09`, value: current });
    }
    for (const category of enabled)
      select.createEl("option", { text: category.name, value: category.name });
    select.value = current;
    select.onchange = () => {
      article.metadata.category = select.value;
      this.dirtyArticles.add(article.id);
    };
  }
  renderEditor(container, article) {
    var _a, _b, _c, _d;
    const heading = container.createDiv({ cls: "vermilion-editor-heading" });
    heading.createEl("h3", { text: "\u7F16\u8F91" });
    const analyzeButton = heading.createEl("button", { text: "AI \u5206\u6790\u5F53\u524D" });
    analyzeButton.disabled = this.aiRunning || article.status === "deleted" || article.status === "conflict";
    analyzeButton.onclick = () => void this.analyzeArticle(article);
    if (article.error)
      container.createDiv({ cls: "vermilion-error", text: article.error });
    this.labeledInput(container, "\u6807\u9898", (_a = article.metadata.title) != null ? _a : "", (value) => {
      article.metadata.title = value;
      this.dirtyArticles.add(article.id);
    });
    this.labeledInput(container, "\u6458\u8981", (_b = article.metadata.description) != null ? _b : "", (value) => {
      article.metadata.description = value;
      this.dirtyArticles.add(article.id);
    }, true);
    this.renderCategorySelect(container, article);
    this.labeledInput(container, "\u6807\u7B7E\uFF08\u9017\u53F7\u5206\u9694\uFF09", ((_c = article.metadata.tags) != null ? _c : []).join(", "), (value) => {
      article.metadata.tags = value.split(/[,，]/).map((tag) => tag.trim()).filter(Boolean);
      this.dirtyArticles.add(article.id);
    });
    this.labeledInput(container, "\u53D1\u5E03\u65F6\u95F4", (_d = article.metadata.published) != null ? _d : "", (value) => {
      article.metadata.published = value;
      this.dirtyArticles.add(article.id);
    });
    const flags = container.createDiv({ cls: "vermilion-flags" });
    for (const [label, key] of [["\u8349\u7A3F", "draft"], ["\u7F6E\u9876", "pinned"]]) {
      const wrapper = flags.createEl("label");
      const checkbox = wrapper.createEl("input", { type: "checkbox" });
      checkbox.checked = Boolean(article.metadata[key]);
      checkbox.onchange = () => {
        article.metadata[key] = checkbox.checked;
        this.dirtyArticles.add(article.id);
      };
      wrapper.appendText(label);
    }
    const bodyField = container.createDiv({ cls: "vermilion-field" });
    bodyField.createEl("label", { text: "\u6B63\u6587" });
    const body = bodyField.createEl("textarea", { cls: "vermilion-body-editor" });
    body.value = article.content;
    body.oninput = () => {
      article.content = body.value;
      this.dirtyArticles.add(article.id);
    };
    if (article.aiSuggestion) {
      const aiBox = container.createDiv({ cls: "vermilion-ai-box" });
      aiBox.createEl("h4", { text: "AI \u5EFA\u8BAE" });
      aiBox.createEl("p", { text: article.aiSuggestion.description || "\u6CA1\u6709\u6458\u8981\u5EFA\u8BAE" });
      aiBox.createEl("p", { text: `\u5206\u7C7B\uFF1A${article.aiSuggestion.category || "\u65E0"}` });
      if (article.aiSuggestion.proposedCategory) {
        aiBox.createEl("p", { text: `\u65B0\u5206\u7C7B\u5EFA\u8BAE\uFF1A${article.aiSuggestion.proposedCategory.name}\uFF08${article.aiSuggestion.proposedCategory.reason || "\u672A\u63D0\u4F9B\u7406\u7531"}\uFF09` });
      }
      aiBox.createEl("p", { text: `\u5DF2\u6709\u6807\u7B7E\uFF1A${article.aiSuggestion.selectedTags.join("\u3001") || "\u65E0"}` });
      aiBox.createEl("button", { text: "\u91C7\u7528\u5DF2\u6709\u5EFA\u8BAE" }).onclick = () => {
        var _a2, _b2, _c2, _d2, _e;
        if ((_a2 = article.aiSuggestion) == null ? void 0 : _a2.description)
          article.metadata.description = article.aiSuggestion.description;
        if ((_b2 = article.aiSuggestion) == null ? void 0 : _b2.category)
          article.metadata.category = article.aiSuggestion.category;
        article.metadata.tags = Array.from(/* @__PURE__ */ new Set([...(_c2 = article.metadata.tags) != null ? _c2 : [], ...(_e = (_d2 = article.aiSuggestion) == null ? void 0 : _d2.selectedTags) != null ? _e : []]));
        this.dirtyArticles.add(article.id);
        void this.cacheAISuggestion(article);
        this.render();
      };
      for (const proposal of article.aiSuggestion.proposedTags) {
        const proposalRow = aiBox.createDiv({ cls: "vermilion-proposal" });
        proposalRow.createSpan({ text: `${proposal.name}\uFF1A${proposal.reason}` });
        proposalRow.createEl("button", { text: "\u6279\u51C6\u65B0\u6807\u7B7E" }).onclick = () => void this.approveProposedTag(article, proposal.name);
      }
    }
    const actions = container.createDiv({ cls: "vermilion-actions" });
    actions.createEl("button", { text: "\u4FDD\u5B58\u5230\u670D\u52A1\u5668\u548C\u672C\u5730", cls: "mod-cta" }).onclick = () => void this.saveArticle(article);
    actions.createEl("button", { text: "\u5728 Obsidian \u4E2D\u6253\u5F00" }).onclick = () => void this.openLocalArticle(article);
  }
  async renderPreview(container, article) {
    var _a, _b, _c;
    container.createEl("h3", { text: "\u9884\u89C8" });
    const meta = container.createDiv({ cls: "vermilion-preview-meta" });
    meta.createEl("strong", { text: article.metadata.title });
    meta.createEl("p", { text: (_a = article.metadata.description) != null ? _a : "" });
    meta.createEl("small", { text: `${(_b = article.metadata.category) != null ? _b : "\u672A\u5206\u7C7B"} \xB7 ${((_c = article.metadata.tags) != null ? _c : []).join("\u3001")}` });
    const markdown = container.createDiv({ cls: "markdown-preview-view" });
    await import_obsidian3.MarkdownRenderer.render(this.app, article.content, markdown, this.localPath(article), this);
  }
  renderTaxonomy(container) {
    const section = container.createDiv({ cls: "vermilion-taxonomy" });
    section.createEl("h3", { text: "\u5206\u7C7B\u4E0E\u6807\u7B7E\u7BA1\u7406" });
    if (this.taxonomyState === "loading") {
      section.createDiv({ cls: "vermilion-state-card", text: "\u6B63\u5728\u52A0\u8F7D\u6807\u7B7E\u5E93\u2026" });
      return;
    }
    if (this.taxonomyState === "error" || !this.taxonomy) {
      const card = section.createDiv({ cls: "vermilion-state-card is-error" });
      card.createEl("strong", { text: "\u6807\u7B7E\u5E93\u52A0\u8F7D\u5931\u8D25" });
      card.createEl("p", { text: this.taxonomyError || "\u672A\u77E5\u9519\u8BEF" });
      const actions = card.createDiv({ cls: "vermilion-actions" });
      actions.createEl("button", { text: "\u91CD\u65B0\u52A0\u8F7D", cls: "mod-cta" }).onclick = () => void this.loadTaxonomy(true);
      actions.createEl("button", { text: "\u68C0\u67E5\u63D2\u4EF6\u8BBE\u7F6E" }).onclick = () => {
        const setting = this.app.setting;
        setting == null ? void 0 : setting.open();
        setting == null ? void 0 : setting.openTabById(this.plugin.manifest.id);
      };
      return;
    }
    const tabs = section.createDiv({ cls: "vermilion-taxonomy-tabs" });
    for (const [label, value] of [["\u5206\u7C7B", "categories"], ["\u6807\u7B7E", "tags"]]) {
      const button = tabs.createEl("button", { text: label, cls: this.taxonomyTab === value ? "mod-cta" : "" });
      button.onclick = () => {
        this.taxonomyTab = value;
        this.render();
      };
    }
    if (this.taxonomyTab === "categories") {
      this.renderCategories(section);
      return;
    }
    section.createEl("p", { text: "\u542F\u7528\u4E14\u5141\u8BB8 AI \u4F7F\u7528\u7684\u6807\u7B7E\u4F1A\u8FDB\u5165 AI \u767D\u540D\u5355\u3002\u5DF2\u88AB\u6587\u7AE0\u4F7F\u7528\u7684\u6807\u7B7E\u8BF7\u505C\u7528\u6216\u6539\u540D\uFF0C\u4E0D\u76F4\u63A5\u5220\u9664\u3002" });
    const enabledCount = this.taxonomy.tags.filter((tag) => tag.enabled).length;
    section.createDiv({ cls: "vermilion-taxonomy-summary", text: `\u5171 ${this.taxonomy.tags.length} \u4E2A\u6807\u7B7E \xB7 ${enabledCount} \u4E2A\u542F\u7528 \xB7 ${this.collectProposals().length} \u4E2A\u5F85\u5BA1\u6279\u5EFA\u8BAE` });
    this.renderProposalQueue(section);
    const toolbar = section.createDiv({ cls: "vermilion-taxonomy-toolbar" });
    const search = toolbar.createEl("input", { type: "search", value: this.tagSearch });
    search.placeholder = "\u641C\u7D22\u540D\u79F0\u3001\u522B\u540D\u6216\u8BF4\u660E";
    const filter = toolbar.createEl("select");
    for (const [label, value] of [["\u5168\u90E8\u6807\u7B7E", "all"], ["\u4EC5\u542F\u7528", "enabled"], ["\u4EC5\u505C\u7528", "disabled"]]) {
      const option = filter.createEl("option", { text: label, value });
      option.selected = value === this.tagFilter;
    }
    const addButton = toolbar.createEl("button", { text: "\u65B0\u589E\u6807\u7B7E" });
    const reloadButton = toolbar.createEl("button", { text: "\u91CD\u65B0\u52A0\u8F7D" });
    const saveButton = toolbar.createEl("button", { text: "\u4FDD\u5B58\u6807\u7B7E\u5E93", cls: "mod-cta" });
    const list = section.createDiv({ cls: "vermilion-tag-list" });
    const updateList = () => this.renderTagList(list);
    search.oninput = () => {
      this.tagSearch = search.value;
      updateList();
    };
    filter.onchange = () => {
      this.tagFilter = filter.value;
      updateList();
    };
    addButton.onclick = () => {
      var _a;
      (_a = this.taxonomy) == null ? void 0 : _a.tags.unshift({ id: "", name: "", aliases: [], description: "", enabled: true, aiSelectable: true, createdAt: "", updatedAt: "" });
      this.tagSearch = "";
      this.tagFilter = "all";
      this.render();
    };
    reloadButton.onclick = () => {
      if (window.confirm("\u91CD\u65B0\u52A0\u8F7D\u4F1A\u4E22\u5F03\u5C1A\u672A\u4FDD\u5B58\u7684\u6807\u7B7E\u4FEE\u6539\uFF0C\u786E\u8BA4\u7EE7\u7EED\u5417\uFF1F"))
        void this.loadTaxonomy(true);
    };
    saveButton.onclick = () => void this.saveTaxonomy();
    updateList();
  }
  renderCategories(container) {
    if (!this.taxonomy)
      return;
    container.createEl("p", { text: "\u6BCF\u7BC7\u6587\u7AE0\u53EA\u80FD\u9009\u62E9\u4E00\u4E2A\u5DF2\u542F\u7528\u5206\u7C7B\u3002\u5DF2\u88AB\u6587\u7AE0\u4F7F\u7528\u7684\u5206\u7C7B\u4E0D\u80FD\u76F4\u63A5\u5220\u9664\u3002" });
    const proposals = this.collectCategoryProposals();
    container.createDiv({ cls: "vermilion-taxonomy-summary", text: `\u5171 ${this.taxonomy.categories.length} \u4E2A\u5206\u7C7B \xB7 ${this.taxonomy.categories.filter((item) => item.enabled).length} \u4E2A\u542F\u7528 \xB7 ${proposals.length} \u4E2A\u5F85\u5BA1\u6279\u5EFA\u8BAE` });
    if (proposals.length) {
      const box = container.createDiv({ cls: "vermilion-proposal-queue" });
      box.createEl("h4", { text: "AI \u65B0\u5206\u7C7B\u5F85\u5BA1\u6279" });
      for (const { article, proposal } of proposals) {
        const row = box.createDiv({ cls: "vermilion-proposal-review" });
        const description = row.createDiv();
        description.createEl("strong", { text: proposal.name });
        description.createEl("small", { text: `${article.metadata.title || article.filename} \xB7 ${proposal.reason || "\u672A\u63D0\u4F9B\u7406\u7531"}` });
        const replacement = row.createEl("select");
        for (const category of this.taxonomy.categories.filter((item) => item.enabled))
          replacement.createEl("option", { text: category.name, value: category.name });
        row.createEl("button", { text: "\u6279\u51C6" }).onclick = () => void this.approveProposedCategory(article, proposal);
        const replace = row.createEl("button", { text: "\u66FF\u6362" });
        replace.disabled = replacement.options.length === 0;
        replace.onclick = () => this.resolveCategoryProposal(article, replacement.value);
        row.createEl("button", { text: "\u62D2\u7EDD" }).onclick = () => this.resolveCategoryProposal(article);
      }
    }
    const actions = container.createDiv({ cls: "vermilion-taxonomy-toolbar compact" });
    actions.createEl("button", { text: "\u65B0\u589E\u5206\u7C7B" }).onclick = () => {
      var _a;
      (_a = this.taxonomy) == null ? void 0 : _a.categories.unshift({ id: "", name: "", description: "", enabled: true });
      this.render();
    };
    actions.createEl("button", { text: "\u91CD\u65B0\u52A0\u8F7D" }).onclick = () => {
      if (window.confirm("\u91CD\u65B0\u52A0\u8F7D\u4F1A\u4E22\u5F03\u5C1A\u672A\u4FDD\u5B58\u7684\u5206\u7C7B\u4FEE\u6539\uFF0C\u786E\u8BA4\u7EE7\u7EED\u5417\uFF1F"))
        void this.loadTaxonomy(true);
    };
    actions.createEl("button", { text: "\u4FDD\u5B58\u5206\u7C7B\u5E93", cls: "mod-cta" }).onclick = () => void this.saveTaxonomy();
    const list = container.createDiv({ cls: "vermilion-tag-list" });
    if (!this.taxonomy.categories.length)
      list.createDiv({ cls: "vermilion-empty compact", text: "\u5206\u7C7B\u5E93\u4E3A\u7A7A\uFF0C\u53EF\u4EE5\u521B\u5EFA\u7B2C\u4E00\u4E2A\u5206\u7C7B\u3002" });
    for (const category of this.taxonomy.categories)
      this.renderCategoryRow(list, category);
  }
  renderCategoryRow(container, category) {
    var _a;
    const row = container.createDiv({ cls: "vermilion-category-row" });
    const identity = row.createDiv({ cls: "vermilion-tag-identity" });
    const name = identity.createEl("input", { type: "text", value: category.name });
    name.placeholder = "\u5206\u7C7B\u540D\u79F0";
    name.oninput = () => category.name = name.value;
    const draftUsage = this.countDraftCategoryUsage(category.name);
    const publishedUsage = (_a = this.categoryUsage[category.name]) != null ? _a : 0;
    identity.createEl("small", { text: this.usageLabel(draftUsage, publishedUsage) });
    const description = row.createEl("input", { type: "text", value: category.description });
    description.placeholder = "\u544A\u8BC9 AI \u4F55\u65F6\u9009\u62E9\u8FD9\u4E2A\u5206\u7C7B";
    description.oninput = () => category.description = description.value;
    const enabledLabel = row.createEl("label");
    const enabled = enabledLabel.createEl("input", { type: "checkbox" });
    enabled.checked = category.enabled;
    enabled.onchange = () => category.enabled = enabled.checked;
    enabledLabel.appendText("\u542F\u7528");
    const remove = row.createEl("button", { text: "\u5220\u9664" });
    const effectiveUsage = draftUsage != null ? draftUsage : this.taxonomyUsageLoaded ? publishedUsage : null;
    remove.disabled = effectiveUsage === null || effectiveUsage > 0;
    remove.title = effectiveUsage === null ? "\u65E0\u6CD5\u786E\u8BA4\u4F7F\u7528\u6B21\u6570\uFF0C\u5DF2\u7981\u6B62\u5220\u9664\u3002" : effectiveUsage > 0 ? "\u5F53\u524D\u5BA1\u6838\u72B6\u6001\u4ECD\u6709\u6587\u7AE0\u4F7F\u7528\u8BE5\u5206\u7C7B\u3002" : "\u5220\u9664\u5206\u7C7B\uFF0C\u5E76\u5C06\u76F8\u5173\u6587\u7AE0\u52A0\u5165\u672C\u6B21\u53D1\u5E03";
    remove.onclick = () => {
      if (!this.taxonomy || !window.confirm(`\u786E\u8BA4\u5220\u9664\u5206\u7C7B\u201C${category.name || "\u672A\u547D\u540D\u5206\u7C7B"}\u201D\u5417\uFF1F`))
        return;
      this.selectArticlesAffectedByCategory(category.name);
      this.taxonomy.categories = this.taxonomy.categories.filter((item) => item !== category);
      this.render();
    };
  }
  renderTagList(container) {
    container.empty();
    if (!this.taxonomy)
      return;
    const query = this.tagSearch.trim().toLowerCase();
    const tags = this.taxonomy.tags.filter((tag) => {
      if (this.tagFilter === "enabled" && !tag.enabled)
        return false;
      if (this.tagFilter === "disabled" && tag.enabled)
        return false;
      return !query || [tag.name, tag.description, ...tag.aliases].some((value) => value.toLowerCase().includes(query));
    });
    if (!tags.length) {
      container.createDiv({ cls: "vermilion-empty compact", text: this.taxonomy.tags.length ? "\u6CA1\u6709\u7B26\u5408\u6761\u4EF6\u7684\u6807\u7B7E\u3002" : "\u6807\u7B7E\u5E93\u4E3A\u7A7A\uFF0C\u53EF\u4EE5\u521B\u5EFA\u7B2C\u4E00\u4E2A\u6807\u7B7E\u3002" });
      return;
    }
    for (const tag of tags)
      this.renderTagRow(container, tag);
  }
  renderTagRow(container, tag) {
    var _a;
    const row = container.createDiv({ cls: "vermilion-tag-row" });
    const identity = row.createDiv({ cls: "vermilion-tag-identity" });
    const name = identity.createEl("input", { type: "text", value: tag.name });
    name.placeholder = "\u6807\u7B7E\u540D\u79F0";
    name.oninput = () => tag.name = name.value;
    const draftUsage = this.countDraftTagUsage(tag.name);
    const publishedUsage = (_a = this.taxonomyUsage[tag.name]) != null ? _a : 0;
    identity.createEl("small", { text: this.usageLabel(draftUsage, publishedUsage) });
    const details = row.createDiv({ cls: "vermilion-tag-details" });
    const description = details.createEl("input", { type: "text", value: tag.description });
    description.placeholder = "\u544A\u8BC9 AI \u4F55\u65F6\u4F7F\u7528\u8FD9\u4E2A\u6807\u7B7E";
    description.oninput = () => tag.description = description.value;
    const aliases = details.createEl("input", { type: "text", value: tag.aliases.join(", ") });
    aliases.placeholder = "\u522B\u540D\uFF08\u9017\u53F7\u5206\u9694\uFF09";
    aliases.oninput = () => tag.aliases = aliases.value.split(/[,，]/).map((value) => value.trim()).filter(Boolean);
    const switches = row.createDiv({ cls: "vermilion-tag-switches" });
    for (const [label, key] of [["\u542F\u7528", "enabled"], ["\u5141\u8BB8 AI", "aiSelectable"]]) {
      const wrapper = switches.createEl("label");
      const checkbox = wrapper.createEl("input", { type: "checkbox" });
      checkbox.checked = tag[key];
      checkbox.onchange = () => tag[key] = checkbox.checked;
      wrapper.appendText(label);
    }
    const remove = row.createEl("button", { text: "\u5220\u9664" });
    const effectiveUsage = draftUsage != null ? draftUsage : this.taxonomyUsageLoaded ? publishedUsage : null;
    remove.disabled = effectiveUsage === null || effectiveUsage > 0;
    remove.title = effectiveUsage === null ? "\u65E0\u6CD5\u786E\u8BA4\u4F7F\u7528\u6B21\u6570\uFF0C\u5DF2\u7981\u6B62\u5220\u9664\u3002" : effectiveUsage > 0 ? "\u5F53\u524D\u5BA1\u6838\u72B6\u6001\u4ECD\u6709\u6587\u7AE0\u4F7F\u7528\u8BE5\u6807\u7B7E\u3002" : "\u5220\u9664\u6807\u7B7E\uFF0C\u5E76\u5C06\u76F8\u5173\u6587\u7AE0\u52A0\u5165\u672C\u6B21\u53D1\u5E03";
    remove.onclick = () => {
      if (!this.taxonomy || !window.confirm(`\u786E\u8BA4\u5220\u9664\u6807\u7B7E\u201C${tag.name || "\u672A\u547D\u540D\u6807\u7B7E"}\u201D\u5417\uFF1F`))
        return;
      this.selectArticlesAffectedByTag(tag.name);
      this.taxonomy.tags = this.taxonomy.tags.filter((item) => item !== tag);
      this.render();
    };
  }
  usageLabel(draftUsage, publishedUsage) {
    const published = this.taxonomyUsageLoaded ? `${publishedUsage}` : "\u672A\u77E5";
    return draftUsage === null ? `\u5DF2\u53D1\u5E03 ${published} \u7BC7\u4F7F\u7528` : `\u5F53\u524D\u4EFB\u52A1 ${draftUsage} \u7BC7 \xB7 \u5DF2\u53D1\u5E03 ${published} \u7BC7`;
  }
  countDraftTagUsage(name) {
    var _a;
    if (!((_a = this.job) == null ? void 0 : _a.articles))
      return null;
    const target = name.trim().toLowerCase();
    return this.job.articles.filter((article) => {
      var _a2;
      return article.status !== "deleted" && ((_a2 = article.metadata.tags) != null ? _a2 : []).some((tag) => tag.trim().toLowerCase() === target);
    }).length;
  }
  countDraftCategoryUsage(name) {
    var _a;
    if (!((_a = this.job) == null ? void 0 : _a.articles))
      return null;
    const target = name.trim().toLowerCase();
    return this.job.articles.filter((article) => {
      var _a2;
      return article.status !== "deleted" && ((_a2 = article.metadata.category) != null ? _a2 : "").trim().toLowerCase() === target;
    }).length;
  }
  selectArticlesAffectedByTag(name) {
    var _a, _b, _c;
    if (!((_a = this.job) == null ? void 0 : _a.articles))
      return;
    const target = name.trim().toLowerCase();
    let added = 0;
    for (const article of this.job.articles) {
      const previouslyUsed = ((_b = article.originalMetadata.tags) != null ? _b : []).some((tag) => tag.trim().toLowerCase() === target);
      const stillUsed = article.status !== "deleted" && ((_c = article.metadata.tags) != null ? _c : []).some((tag) => tag.trim().toLowerCase() === target);
      if (previouslyUsed && !stillUsed && !this.selected.has(article.id)) {
        this.selected.add(article.id);
        added++;
      }
    }
    if (added)
      new import_obsidian3.Notice(`\u5DF2\u81EA\u52A8\u9009\u62E9 ${added} \u7BC7\u53D7\u6807\u7B7E\u201C${name}\u201D\u5F71\u54CD\u7684\u6587\u7AE0\uFF0C\u8BF7\u786E\u8BA4\u4FDD\u5B58\u540E\u4E00\u8D77\u53D1\u5E03\u3002`);
  }
  selectArticlesAffectedByCategory(name) {
    var _a, _b, _c;
    if (!((_a = this.job) == null ? void 0 : _a.articles))
      return;
    const target = name.trim().toLowerCase();
    let added = 0;
    for (const article of this.job.articles) {
      const previouslyUsed = ((_b = article.originalMetadata.category) != null ? _b : "").trim().toLowerCase() === target;
      const stillUsed = article.status !== "deleted" && ((_c = article.metadata.category) != null ? _c : "").trim().toLowerCase() === target;
      if (previouslyUsed && !stillUsed && !this.selected.has(article.id)) {
        this.selected.add(article.id);
        added++;
      }
    }
    if (added)
      new import_obsidian3.Notice(`\u5DF2\u81EA\u52A8\u9009\u62E9 ${added} \u7BC7\u53D7\u5206\u7C7B\u201C${name}\u201D\u5F71\u54CD\u7684\u6587\u7AE0\uFF0C\u8BF7\u786E\u8BA4\u4FDD\u5B58\u540E\u4E00\u8D77\u53D1\u5E03\u3002`);
  }
  collectProposals() {
    var _a, _b, _c, _d;
    const result = [];
    for (const article of (_b = (_a = this.job) == null ? void 0 : _a.articles) != null ? _b : []) {
      for (const proposal of (_d = (_c = article.aiSuggestion) == null ? void 0 : _c.proposedTags) != null ? _d : [])
        result.push({ article, proposal });
    }
    return result;
  }
  collectCategoryProposals() {
    var _a, _b, _c;
    const result = [];
    for (const article of (_b = (_a = this.job) == null ? void 0 : _a.articles) != null ? _b : []) {
      if ((_c = article.aiSuggestion) == null ? void 0 : _c.proposedCategory)
        result.push({ article, proposal: article.aiSuggestion.proposedCategory });
    }
    return result;
  }
  async approveProposedCategory(article, proposal) {
    if (!this.taxonomy)
      return;
    let category = this.taxonomy.categories.find((item) => item.name.toLowerCase() === proposal.name.toLowerCase());
    if (!category) {
      category = { id: "", name: proposal.name, description: proposal.reason, enabled: true };
      this.taxonomy.categories.push(category);
      if (!await this.saveTaxonomy(false))
        return;
    }
    article.metadata.category = category.name;
    if (article.aiSuggestion)
      article.aiSuggestion.proposedCategory = null;
    void this.cacheAISuggestion(article);
    this.dirtyArticles.add(article.id);
    this.render();
    new import_obsidian3.Notice(`\u5DF2\u6279\u51C6\u5206\u7C7B\u201C${category.name}\u201D\uFF0C\u4FDD\u5B58\u6587\u7AE0\u540E\u751F\u6548\u3002`);
  }
  resolveCategoryProposal(article, replacement) {
    var _a, _b, _c;
    const proposedName = (_c = (_b = (_a = article.aiSuggestion) == null ? void 0 : _a.proposedCategory) == null ? void 0 : _b.name) != null ? _c : "\u65B0\u5206\u7C7B";
    if (replacement) {
      article.metadata.category = replacement;
      this.dirtyArticles.add(article.id);
    }
    if (article.aiSuggestion)
      article.aiSuggestion.proposedCategory = null;
    void this.cacheAISuggestion(article);
    this.render();
    new import_obsidian3.Notice(replacement ? `\u5DF2\u5C06\u201C${proposedName}\u201D\u66FF\u6362\u4E3A\u201C${replacement}\u201D\u3002` : `\u5DF2\u62D2\u7EDD\u65B0\u5206\u7C7B\u201C${proposedName}\u201D\u3002`);
  }
  renderProposalQueue(container) {
    var _a, _b;
    const proposals = this.collectProposals();
    if (!proposals.length)
      return;
    const box = container.createDiv({ cls: "vermilion-proposal-queue" });
    box.createEl("h4", { text: "AI \u65B0\u6807\u7B7E\u5F85\u5BA1\u6279" });
    for (const { article, proposal } of proposals) {
      const row = box.createDiv({ cls: "vermilion-proposal-review" });
      const description = row.createDiv();
      description.createEl("strong", { text: proposal.name });
      description.createEl("small", { text: `${article.metadata.title || article.filename} \xB7 ${proposal.reason || "\u672A\u63D0\u4F9B\u7406\u7531"}` });
      const replacement = row.createEl("select");
      for (const tag of (_b = (_a = this.taxonomy) == null ? void 0 : _a.tags.filter((item) => item.enabled)) != null ? _b : [])
        replacement.createEl("option", { text: tag.name, value: tag.name });
      row.createEl("button", { text: "\u6279\u51C6" }).onclick = () => void this.approveProposedTag(article, proposal.name);
      const replace = row.createEl("button", { text: "\u66FF\u6362" });
      replace.disabled = replacement.options.length === 0;
      replace.onclick = () => this.resolveProposal(article, proposal.name, replacement.value);
      row.createEl("button", { text: "\u62D2\u7EDD" }).onclick = () => this.resolveProposal(article, proposal.name);
    }
  }
  resolveProposal(article, proposedName, replacement) {
    var _a;
    if (replacement) {
      article.metadata.tags = Array.from(/* @__PURE__ */ new Set([...(_a = article.metadata.tags) != null ? _a : [], replacement]));
      this.dirtyArticles.add(article.id);
    }
    if (article.aiSuggestion)
      article.aiSuggestion.proposedTags = article.aiSuggestion.proposedTags.filter((tag) => tag.name !== proposedName);
    void this.cacheAISuggestion(article);
    this.render();
    new import_obsidian3.Notice(replacement ? `\u5DF2\u5C06\u201C${proposedName}\u201D\u66FF\u6362\u4E3A\u201C${replacement}\u201D\u3002` : `\u5DF2\u62D2\u7EDD\u65B0\u6807\u7B7E\u201C${proposedName}\u201D\u3002`);
  }
  async approveProposedTag(article, name) {
    var _a;
    if (!this.taxonomy) {
      new import_obsidian3.Notice("\u6807\u7B7E\u5E93\u672A\u52A0\u8F7D\uFF0C\u6682\u65F6\u65E0\u6CD5\u6279\u51C6\u65B0\u6807\u7B7E\u3002");
      return;
    }
    if (!this.taxonomy.tags.some((tag) => tag.name.toLowerCase() === name.toLowerCase())) {
      this.taxonomy.tags.push({ id: "", name, aliases: [], description: "", enabled: true, aiSelectable: true, createdAt: "", updatedAt: "" });
      if (!await this.saveTaxonomy(false))
        return;
    }
    article.metadata.tags = Array.from(/* @__PURE__ */ new Set([...(_a = article.metadata.tags) != null ? _a : [], name]));
    this.dirtyArticles.add(article.id);
    if (article.aiSuggestion)
      article.aiSuggestion.proposedTags = article.aiSuggestion.proposedTags.filter((tag) => tag.name !== name);
    void this.cacheAISuggestion(article);
    this.render();
    new import_obsidian3.Notice(`\u5DF2\u6279\u51C6\u6807\u7B7E\u201C${name}\u201D\uFF0C\u4FDD\u5B58\u6587\u7AE0\u540E\u751F\u6548\u3002`);
  }
  async saveTaxonomy(notify = true) {
    var _a, _b;
    if (!this.taxonomy)
      return false;
    const names = this.taxonomy.tags.map((tag) => tag.name.trim());
    if (names.some((name) => !name)) {
      new import_obsidian3.Notice("\u6807\u7B7E\u540D\u79F0\u4E0D\u80FD\u4E3A\u7A7A\u3002");
      return false;
    }
    const normalized = names.map((name) => name.toLowerCase());
    if (new Set(normalized).size !== normalized.length) {
      new import_obsidian3.Notice("\u6807\u7B7E\u540D\u79F0\u4E0D\u80FD\u91CD\u590D\uFF0C\u8BF7\u5148\u5408\u5E76\u6216\u6539\u540D\u3002");
      return false;
    }
    const categoryNames = this.taxonomy.categories.map((category) => category.name.trim());
    if (categoryNames.some((name) => !name)) {
      new import_obsidian3.Notice("\u5206\u7C7B\u540D\u79F0\u4E0D\u80FD\u4E3A\u7A7A\u3002");
      return false;
    }
    const normalizedCategories = categoryNames.map((name) => name.toLowerCase());
    if (new Set(normalizedCategories).size !== normalizedCategories.length) {
      new import_obsidian3.Notice("\u5206\u7C7B\u540D\u79F0\u4E0D\u80FD\u91CD\u590D\uFF0C\u8BF7\u5148\u5408\u5E76\u6216\u6539\u540D\u3002");
      return false;
    }
    try {
      this.taxonomy = await this.plugin.api.saveTaxonomy(this.taxonomy);
      try {
        const usage = await this.plugin.api.getTaxonomyUsage();
        this.taxonomyUsage = (_a = usage.tags) != null ? _a : {};
        this.categoryUsage = (_b = usage.categories) != null ? _b : {};
        this.taxonomyUsageLoaded = true;
      } catch (e) {
        this.taxonomyUsageLoaded = false;
      }
      if (notify)
        new import_obsidian3.Notice("\u5206\u7C7B\u4E0E\u6807\u7B7E\u5E93\u5DF2\u4FDD\u5B58\uFF0C\u968F\u4E0B\u4E00\u6B21\u53D1\u5E03\u8FDB\u5165 Git\u3002");
      this.render();
      return true;
    } catch (error) {
      new import_obsidian3.Notice(`\u4FDD\u5B58\u6807\u7B7E\u5E93\u5931\u8D25\uFF1A${describeApiError(error)}`);
      return false;
    }
  }
  applyCachedSuggestions() {
    var _a;
    if (!this.job || this.plugin.settings.aiSuggestionJobId !== this.job.id)
      return;
    for (const article of (_a = this.job.articles) != null ? _a : []) {
      const cached = this.plugin.settings.aiSuggestions[article.id];
      if (cached)
        article.aiSuggestion = cached;
    }
  }
  needsLocalAI(article) {
    var _a, _b, _c;
    return article.status !== "deleted" && article.status !== "conflict" && !article.aiSuggestion && (article.status === "new" || !((_a = article.metadata.description) == null ? void 0 : _a.trim()) || !((_b = article.metadata.category) == null ? void 0 : _b.trim()) || ((_c = article.metadata.tags) != null ? _c : []).length === 0);
  }
  async cacheAISuggestion(article) {
    if (!this.job || !article.aiSuggestion)
      return;
    if (this.plugin.settings.aiSuggestionJobId !== this.job.id) {
      this.plugin.settings.aiSuggestionJobId = this.job.id;
      this.plugin.settings.aiSuggestions = {};
    }
    this.plugin.settings.aiSuggestions[article.id] = article.aiSuggestion;
    await this.plugin.saveSettings();
  }
  async generateSuggestion(article) {
    if (!this.taxonomy)
      throw new Error("\u5206\u7C7B\u4E0E\u6807\u7B7E\u5E93\u5C1A\u672A\u52A0\u8F7D\u3002");
    article.aiSuggestion = await analyzeArticleLocally(this.plugin.settings, this.taxonomy, article);
    await this.cacheAISuggestion(article);
  }
  async analyzeArticle(article) {
    if (this.aiRunning)
      return;
    this.aiRunning = true;
    this.aiProgress = `\u6B63\u5728\u5206\u6790\uFF1A${article.metadata.title || article.filename}`;
    this.render();
    try {
      await this.generateSuggestion(article);
      new import_obsidian3.Notice(`AI \u5206\u6790\u5B8C\u6210\uFF1A${article.metadata.title || article.filename}`);
    } catch (error) {
      new import_obsidian3.Notice(`AI \u5206\u6790\u5931\u8D25\uFF1A${error instanceof Error ? error.message : String(error)}`);
    } finally {
      this.aiRunning = false;
      this.aiProgress = "";
      this.render();
    }
  }
  async analyzePendingArticles() {
    var _a;
    if (this.aiRunning || !((_a = this.job) == null ? void 0 : _a.articles))
      return;
    const articles = this.job.articles.filter((article) => this.needsLocalAI(article));
    if (!articles.length) {
      new import_obsidian3.Notice("\u6CA1\u6709\u9700\u8981 AI \u5206\u6790\u7684\u6587\u7AE0\uFF1B\u53EF\u4EE5\u5728\u6587\u7AE0\u7F16\u8F91\u533A\u624B\u52A8\u91CD\u65B0\u5206\u6790\u5F53\u524D\u6587\u7AE0\u3002");
      return;
    }
    if (!this.taxonomy) {
      new import_obsidian3.Notice("\u5206\u7C7B\u4E0E\u6807\u7B7E\u5E93\u5C1A\u672A\u52A0\u8F7D\u3002");
      return;
    }
    if (!this.plugin.settings.aiApiKey.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u914D\u7F6E AI API Key\u3002");
      return;
    }
    this.aiRunning = true;
    const errors = [];
    this.render();
    for (let index = 0; index < articles.length; index++) {
      const article = articles[index];
      this.aiProgress = `\u672C\u5730 AI \u5206\u6790 ${index + 1}/${articles.length}\uFF1A${article.metadata.title || article.filename}`;
      this.render();
      try {
        await this.generateSuggestion(article);
      } catch (error) {
        errors.push(`${article.metadata.title || article.filename}\uFF1A${error instanceof Error ? error.message : String(error)}`);
      }
    }
    this.aiRunning = false;
    this.aiProgress = "";
    this.render();
    if (errors.length)
      new import_obsidian3.Notice(`AI \u5206\u6790\u5B8C\u6210\uFF0C\u4F46\u6709 ${errors.length} \u7BC7\u5931\u8D25\uFF1A${errors[0]}`);
    else
      new import_obsidian3.Notice(`\u672C\u5730 AI \u5206\u6790\u5B8C\u6210\uFF1A${articles.length} \u7BC7\u6587\u7AE0\u3002`);
  }
  async saveArticle(article) {
    var _a, _b;
    if (!this.job)
      return;
    try {
      await this.assertLocalNotChanged(article);
      const suggestion = article.aiSuggestion;
      const updated = await this.plugin.api.updateArticle(this.job.id, article);
      updated.aiSuggestion = suggestion;
      const index = (_b = (_a = this.job.articles) == null ? void 0 : _a.findIndex((item) => item.id === article.id)) != null ? _b : -1;
      if (index >= 0 && this.job.articles)
        this.job.articles[index] = updated;
      this.activeArticleId = updated.id;
      await this.writeLocalArticle(updated);
      updated.clientHash = await sha256(this.composeMarkdown(updated));
      this.dirtyArticles.delete(updated.id);
      this.render();
      new import_obsidian3.Notice(`\u5DF2\u4FDD\u5B58\uFF1A${updated.metadata.title}`);
    } catch (error) {
      new import_obsidian3.Notice(`\u4FDD\u5B58\u5931\u8D25\uFF1A${error.message}`);
    }
  }
  async publishSelected() {
    var _a;
    if (!((_a = this.job) == null ? void 0 : _a.articles))
      return;
    const articles = this.job.articles.filter((article) => this.selected.has(article.id));
    if (articles.some((article) => this.dirtyArticles.has(article.id))) {
      new import_obsidian3.Notice("\u6240\u9009\u6587\u7AE0\u5B58\u5728\u672A\u4FDD\u5B58\u4FEE\u6539\uFF0C\u8BF7\u5148\u4FDD\u5B58\u5230\u670D\u52A1\u5668\u548C\u672C\u5730\u3002");
      return;
    }
    if (articles.some((article) => article.status === "deleted") && !window.confirm("\u6240\u9009\u5185\u5BB9\u5305\u542B\u5F85\u5220\u9664\u6587\u7AE0\uFF0C\u786E\u8BA4\u4ECE\u7F51\u7AD9\u5220\u9664\u5417\uFF1F"))
      return;
    if (!window.confirm(`\u786E\u8BA4\u76F4\u63A5\u53D1\u5E03 ${articles.length} \u7BC7\u6587\u7AE0\u5230 deploy \u5417\uFF1F`))
      return;
    try {
      if (!await this.saveTaxonomy(false))
        return;
      const response = await this.plugin.api.publish(this.job.id, articles);
      new import_obsidian3.Notice(`\u53D1\u5E03\u6210\u529F\uFF1A${response.commitSha.slice(0, 12)}`);
      this.selected.clear();
      await this.refreshJob();
    } catch (error) {
      new import_obsidian3.Notice(`\u53D1\u5E03\u5931\u8D25\uFF1A${error.message}`);
    }
  }
  localPath(article) {
    return (0, import_obsidian3.normalizePath)([this.plugin.settings.localPostsFolder, article.filename].filter(Boolean).join("/"));
  }
  async collectLocalManifest() {
    const prefix = this.plugin.settings.localPostsFolder ? (0, import_obsidian3.normalizePath)(this.plugin.settings.localPostsFolder) + "/" : "";
    const files = this.app.vault.getFiles().filter((file) => file.path.startsWith(prefix) && /\.mdx?$/i.test(file.path));
    return Promise.all(files.map(async (file) => ({ path: file.path, hash: await sha256(await this.app.vault.read(file)) })));
  }
  composeMarkdown(article) {
    var _a;
    const metadata = { ...(_a = article.metadata.extra) != null ? _a : {} };
    for (const [key, value] of Object.entries(article.metadata)) {
      if (key !== "extra" && value !== void 0 && value !== "")
        metadata[key] = value;
    }
    return `---
${(0, import_obsidian3.stringifyYaml)(metadata).trim()}
---

${article.content.trim()}
`;
  }
  async ensureFolder(path) {
    const parts = path.split("/").slice(0, -1);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current))
        await this.app.vault.createFolder(current);
    }
  }
  async assertLocalNotChanged(article) {
    if (!article.clientHash)
      return;
    const file = this.app.vault.getAbstractFileByPath(this.localPath(article));
    if (!(file instanceof import_obsidian3.TFile))
      throw new Error("\u672C\u5730\u6587\u4EF6\u5DF2\u88AB\u5220\u9664\uFF0C\u8BF7\u91CD\u65B0\u5904\u7406\u4EFB\u52A1\u3002");
    const currentHash = await sha256(await this.app.vault.read(file));
    if (currentHash !== article.clientHash)
      throw new Error("\u672C\u5730\u6587\u4EF6\u5728\u4EFB\u52A1\u5F00\u59CB\u540E\u53D1\u751F\u4E86\u53D8\u5316\uFF0C\u5DF2\u963B\u6B62\u8986\u76D6\uFF0C\u8BF7\u91CD\u65B0\u5904\u7406\u4EFB\u52A1\u3002");
  }
  async writeLocalArticle(article) {
    const path = this.localPath(article);
    await this.ensureFolder(path);
    const markdown = this.composeMarkdown(article);
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian3.TFile)
      await this.app.vault.modify(existing, markdown);
    else
      await this.app.vault.create(path, markdown);
  }
  async openLocalArticle(article) {
    const file = this.app.vault.getAbstractFileByPath(this.localPath(article));
    if (file instanceof import_obsidian3.TFile)
      await this.app.workspace.getLeaf(true).openFile(file);
    else
      new import_obsidian3.Notice("\u672C\u5730\u6587\u4EF6\u4E0D\u5B58\u5728\uFF0C\u8BF7\u5148\u4FDD\u5B58\u5230\u672C\u5730\u3002");
  }
};

// main.ts
var DEFAULT_AI_SYSTEM_PROMPT = "\u4F60\u662F\u201C\u4E00\u4E2A\u95EA\u5FF5\u201D\u7684\u6587\u7AE0\u7F16\u8F91\u52A9\u624B\u3002\u8BF7\u51C6\u786E\u3001\u514B\u5236\u5730\u6574\u7406\u6587\u7AE0\u4FE1\u606F\uFF0C\u4E0D\u8981\u865A\u6784\u6587\u7AE0\u4E2D\u4E0D\u5B58\u5728\u7684\u4E8B\u5B9E\u3002";
var DEFAULT_AI_METADATA_PROMPT = "\u6839\u636E\u6587\u7AE0\u6B63\u6587\u751F\u6210\u7B80\u6D01\u6458\u8981\uFF0C\u5E76\u4ECE\u5DF2\u6709\u5206\u7C7B\u548C\u6807\u7B7E\u4E2D\u9009\u62E9\u6700\u5408\u9002\u7684\u9879\u76EE\u3002\u8F93\u51FA\u5FC5\u987B\u7B26\u5408\u63D2\u4EF6\u8981\u6C42\u7684 JSON \u683C\u5F0F\u3002";
var DEFAULT_AI_TAG_RULES = "\u4F18\u5148\u9009\u62E9\u5DF2\u6709\u6807\u7B7E\u3002\u53EA\u6709\u73B0\u6709\u6807\u7B7E\u786E\u5B9E\u65E0\u6CD5\u8868\u8FBE\u6587\u7AE0\u4E3B\u9898\u65F6\u624D\u63D0\u51FA\u65B0\u6807\u7B7E\uFF1B\u65B0\u6807\u7B7E\u5E94\u7B80\u77ED\u3001\u7A33\u5B9A\u3001\u53EF\u590D\u7528\uFF0C\u907F\u514D\u540C\u4E49\u8BCD\u548C\u8FC7\u7EC6\u7684\u4E34\u65F6\u6807\u7B7E\u3002";
var DEFAULT_SETTINGS = {
  syncEndpoint: "http://localhost:3001/api/sync",
  webhookSecret: "",
  localPostsFolder: "",
  activeJobId: "",
  aiBaseUrl: "https://api.openai.com/v1",
  aiApiKey: "",
  aiModel: "gpt-4o-mini",
  aiSystemPrompt: DEFAULT_AI_SYSTEM_PROMPT,
  aiMetadataPrompt: DEFAULT_AI_METADATA_PROMPT,
  aiTagRules: DEFAULT_AI_TAG_RULES,
  aiMaxProposedTags: 3,
  aiSuggestionJobId: "",
  aiSuggestions: {}
};
var SyncPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.api = new ApiClient(this.settings);
    this.registerView(ARTICLE_MANAGER_VIEW, (leaf) => new ArticleManagerView(leaf, this));
    this.addRibbonIcon("layout-dashboard", "\u4E00\u4E2A\u95EA\u5FF5\uFF1A\u5185\u5BB9\u7BA1\u7406", () => {
      void this.activateManagerView();
    });
    this.addCommand({
      id: "open-flash-thought-content-manager",
      name: "\u6253\u5F00\u201C\u4E00\u4E2A\u95EA\u5FF5\u201D\u5185\u5BB9\u7BA1\u7406",
      callback: () => void this.activateManagerView()
    });
    this.addCommand({
      id: "prepare-flash-thought-sync",
      name: "\u83B7\u53D6\u5E76\u5904\u7406\u6587\u7AE0",
      callback: async () => {
        var _a;
        await this.activateManagerView();
        const view = (_a = this.app.workspace.getLeavesOfType(ARTICLE_MANAGER_VIEW)[0]) == null ? void 0 : _a.view;
        if (view instanceof ArticleManagerView)
          await view.prepareSync();
      }
    });
    this.addSettingTab(new SyncSettingTab(this.app, this));
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(ARTICLE_MANAGER_VIEW);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.api = new ApiClient(this.settings);
  }
  async testServerConnection() {
    if (!this.settings.syncEndpoint.trim())
      throw new Error("\u8BF7\u5148\u586B\u5199\u540C\u6B65\u670D\u52A1\u5730\u5740\u3002");
    if (!this.settings.webhookSecret.trim())
      throw new Error("\u8BF7\u5148\u586B\u5199 Webhook Secret\u3002");
    const taxonomy = await this.api.testConnection();
    return `\u8FDE\u63A5\u6210\u529F\uFF1A\u5DF2\u8BFB\u53D6 ${taxonomy.tags.length} \u4E2A\u6807\u7B7E\u3001${taxonomy.categories.length} \u4E2A\u5206\u7C7B\u3002`;
  }
  async testAIConnection() {
    var _a, _b, _c;
    const baseUrl = this.settings.aiBaseUrl.trim().replace(/\/+$/, "");
    const apiKey = this.settings.aiApiKey.trim();
    const model = this.settings.aiModel.trim();
    if (!baseUrl)
      throw new Error("\u8BF7\u5148\u586B\u5199 AI API \u5730\u5740\u3002");
    if (!apiKey)
      throw new Error("\u8BF7\u5148\u586B\u5199 AI API Key\u3002");
    if (!model)
      throw new Error("\u8BF7\u5148\u586B\u5199\u6A21\u578B\u540D\u79F0\u3002");
    const endpoint = /\/chat\/completions$/i.test(baseUrl) ? baseUrl : `${baseUrl}/chat/completions`;
    const response = await (0, import_obsidian4.requestUrl)({
      url: endpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: this.settings.aiSystemPrompt || DEFAULT_AI_SYSTEM_PROMPT },
          { role: "user", content: "\u8FD9\u662F\u8FDE\u63A5\u6D4B\u8BD5\u3002\u8BF7\u53EA\u56DE\u590D OK\u3002" }
        ],
        max_tokens: 8
      }),
      throw: false
    });
    if (response.status < 200 || response.status >= 300) {
      let message = response.text || `HTTP ${response.status}`;
      try {
        const data = JSON.parse(response.text);
        message = (_c = (_b = (_a = data.error) == null ? void 0 : _a.message) != null ? _b : data.message) != null ? _c : message;
      } catch (e) {
      }
      throw new Error(`HTTP ${response.status}\uFF1A${message}`);
    }
    return `AI \u8FDE\u63A5\u6210\u529F\uFF0C\u6A21\u578B\uFF1A${model}`;
  }
  async activateManagerView() {
    let leaf = this.app.workspace.getLeavesOfType(ARTICLE_MANAGER_VIEW)[0];
    if (!leaf) {
      leaf = this.app.workspace.getLeaf(true);
      await leaf.setViewState({ type: ARTICLE_MANAGER_VIEW, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
};
var SyncSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u4E00\u4E2A\u95EA\u5FF5 \xB7 \u5185\u5BB9\u7BA1\u7406" });
    containerEl.createEl("h3", { text: "\u670D\u52A1\u5668\u8FDE\u63A5" });
    new import_obsidian4.Setting(containerEl).setName("\u540C\u6B65\u670D\u52A1\u5730\u5740").setDesc("\u53EF\u4EE5\u586B\u5199\u670D\u52A1\u5668\u6839\u5730\u5740\u3001/api/sync \u6216 /api/v1\u3002").addText((text2) => text2.setPlaceholder("https://example.com/api/sync").setValue(this.plugin.settings.syncEndpoint).onChange(async (value) => {
      this.plugin.settings.syncEndpoint = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Webhook Secret").setDesc("\u670D\u52A1\u5668 WEBHOOK_SECRET\uFF0C\u7528\u4E8E\u9A8C\u8BC1\u7BA1\u7406\u548C\u53D1\u5E03\u8BF7\u6C42\uFF1B\u5B83\u4E0E AI Key \u76F8\u4E92\u72EC\u7ACB\u3002").addText((text2) => {
      text2.inputEl.type = "password";
      text2.setPlaceholder("\u8F93\u5165\u670D\u52A1\u5668\u5BC6\u94A5").setValue(this.plugin.settings.webhookSecret).onChange(async (value) => {
        this.plugin.settings.webhookSecret = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u8FDE\u63A5\u6D4B\u8BD5").setDesc("\u9A8C\u8BC1\u670D\u52A1\u5730\u5740\u548C Webhook Secret\uFF0C\u5E76\u8BFB\u53D6\u6807\u7B7E\u5E93\u3002").addButton((button) => button.setButtonText("\u6D4B\u8BD5\u670D\u52A1\u5668\u8FDE\u63A5").setCta().onClick(async () => {
      button.setDisabled(true).setButtonText("\u6D4B\u8BD5\u4E2D\u2026");
      try {
        new import_obsidian4.Notice(await this.plugin.testServerConnection());
      } catch (error) {
        new import_obsidian4.Notice(`\u670D\u52A1\u5668\u8FDE\u63A5\u5931\u8D25\uFF1A${describeApiError(error)}`);
      } finally {
        button.setDisabled(false).setButtonText("\u6D4B\u8BD5\u670D\u52A1\u5668\u8FDE\u63A5");
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("\u672C\u5730\u6587\u7AE0\u76EE\u5F55").setDesc("Obsidian Vault \u5185\u4FDD\u5B58\u535A\u5BA2\u6587\u7AE0\u7684\u76EE\u5F55\uFF0C\u4F8B\u5982 Blog/Posts\u3002\u7559\u7A7A\u8868\u793A Vault \u6839\u76EE\u5F55\u3002").addText((text2) => text2.setPlaceholder("Blog/Posts").setValue(this.plugin.settings.localPostsFolder).onChange(async (value) => {
      this.plugin.settings.localPostsFolder = value.replace(/^\/+|\/+$/g, "");
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u672C\u5730 AI \u914D\u7F6E" });
    containerEl.createEl("p", {
      text: "AI \u8BF7\u6C42\u5C06\u7531 Obsidian \u76F4\u63A5\u53D1\u9001\u3002API Key \u53EA\u4FDD\u5B58\u5728\u672C\u673A\u63D2\u4EF6 data.json \u4E2D\uFF0C\u4E0D\u4F1A\u4E0A\u4F20\u5230\u670D\u52A1\u5668\u6216 Git\uFF1B\u8BE5\u6587\u4EF6\u4E0D\u662F\u52A0\u5BC6\u4FDD\u9669\u5E93\uFF0C\u8BF7\u786E\u4FDD\u8BBE\u5907\u548C Vault \u53EF\u4FE1\u3002",
      cls: "setting-item-description"
    });
    new import_obsidian4.Setting(containerEl).setName("AI API \u5730\u5740").setDesc("OpenAI \u517C\u5BB9\u63A5\u53E3\u7684 Base URL\uFF0C\u4F8B\u5982 https://api.openai.com/v1\u3002").addText((text2) => text2.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.aiBaseUrl).onChange(async (value) => {
      this.plugin.settings.aiBaseUrl = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("AI API Key").setDesc("\u4EC5\u4FDD\u5B58\u5728 Obsidian \u63D2\u4EF6\u7684\u672C\u5730\u914D\u7F6E\u4E2D\u3002").addText((text2) => {
      text2.inputEl.type = "password";
      text2.setPlaceholder("\u8F93\u5165 AI API Key").setValue(this.plugin.settings.aiApiKey).onChange(async (value) => {
        this.plugin.settings.aiApiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u586B\u5199\u670D\u52A1\u5546\u652F\u6301\u7684\u6A21\u578B ID\u3002").addText((text2) => text2.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.aiModel).onChange(async (value) => {
      this.plugin.settings.aiModel = value.trim();
      await this.plugin.saveSettings();
    }));
    this.addPromptSetting(containerEl, "\u7CFB\u7EDF\u63D0\u793A\u8BCD", "\u89C4\u5B9A AI \u7684\u8EAB\u4EFD\u3001\u8BED\u6C14\u548C\u57FA\u672C\u8FB9\u754C\u3002", "aiSystemPrompt");
    this.addPromptSetting(containerEl, "\u6587\u7AE0\u4FE1\u606F\u63D0\u793A\u8BCD", "\u89C4\u5B9A\u6807\u9898\u3001\u6458\u8981\u548C\u5206\u7C7B\u7B49\u4FE1\u606F\u5982\u4F55\u751F\u6210\u3002", "aiMetadataPrompt");
    this.addPromptSetting(containerEl, "\u6807\u7B7E\u89C4\u5219", "\u9650\u5236 AI \u5982\u4F55\u9009\u62E9\u5DF2\u6709\u6807\u7B7E\u53CA\u63D0\u51FA\u65B0\u6807\u7B7E\u3002", "aiTagRules");
    new import_obsidian4.Setting(containerEl).setName("\u6700\u591A\u63D0\u51FA\u7684\u65B0\u6807\u7B7E\u6570").setDesc("\u9650\u5236\u5355\u7BC7\u6587\u7AE0\u4E2D AI \u53EF\u63D0\u51FA\u7684\u65B0\u6807\u7B7E\u6570\u91CF\uFF0C\u8303\u56F4 0\u201310\u3002").addText((text2) => {
      text2.inputEl.type = "number";
      text2.inputEl.min = "0";
      text2.inputEl.max = "10";
      text2.setValue(String(this.plugin.settings.aiMaxProposedTags)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        if (Number.isFinite(parsed)) {
          this.plugin.settings.aiMaxProposedTags = Math.max(0, Math.min(10, parsed));
          await this.plugin.saveSettings();
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setName("AI \u914D\u7F6E\u64CD\u4F5C").setDesc("\u8FDE\u63A5\u6D4B\u8BD5\u4F1A\u53D1\u9001\u4E00\u6761\u6781\u77ED\u7684\u6D4B\u8BD5\u6D88\u606F\uFF1B\u6062\u590D\u9ED8\u8BA4\u503C\u4E0D\u4F1A\u6E05\u9664 API Key\u3002").addButton((button) => button.setButtonText("\u6D4B\u8BD5 AI \u8FDE\u63A5").setCta().onClick(async () => {
      button.setDisabled(true).setButtonText("\u6D4B\u8BD5\u4E2D\u2026");
      try {
        new import_obsidian4.Notice(await this.plugin.testAIConnection());
      } catch (error) {
        new import_obsidian4.Notice(`AI \u8FDE\u63A5\u5931\u8D25\uFF1A${error instanceof Error ? error.message : String(error)}`);
      } finally {
        button.setDisabled(false).setButtonText("\u6D4B\u8BD5 AI \u8FDE\u63A5");
      }
    })).addButton((button) => button.setButtonText("\u6062\u590D\u9ED8\u8BA4\u63D0\u793A\u8BCD").setWarning().onClick(async () => {
      if (!window.confirm("\u786E\u8BA4\u6062\u590D\u9ED8\u8BA4\u63D0\u793A\u8BCD\u548C\u65B0\u6807\u7B7E\u6570\u91CF\u5417\uFF1FAI API Key \u4E0D\u4F1A\u88AB\u6E05\u9664\u3002"))
        return;
      this.plugin.settings.aiSystemPrompt = DEFAULT_AI_SYSTEM_PROMPT;
      this.plugin.settings.aiMetadataPrompt = DEFAULT_AI_METADATA_PROMPT;
      this.plugin.settings.aiTagRules = DEFAULT_AI_TAG_RULES;
      this.plugin.settings.aiMaxProposedTags = DEFAULT_SETTINGS.aiMaxProposedTags;
      await this.plugin.saveSettings();
      this.display();
      new import_obsidian4.Notice("\u5DF2\u6062\u590D\u9ED8\u8BA4\u63D0\u793A\u8BCD\u3002");
    }));
  }
  addPromptSetting(containerEl, name, description, key) {
    new import_obsidian4.Setting(containerEl).setName(name).setDesc(description).addTextArea((text2) => {
      text2.inputEl.rows = 5;
      text2.setValue(this.plugin.settings[key]).onChange(async (value) => {
        this.plugin.settings[key] = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
